name: Run Python Test Script

on:
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have any dependencies listed in a requirements.txt file

    - name: Run the test_data_compression.py script
      run: |
        pytest --tb=line --disable-warnings
